### ISSUE TITLE
2016-model

### ISSUE THREAD

**Issue by hdersch** [ottokiksmaler/gear360_modding#1]
I wonder whether you have any idea for the 2016 model, see here: https://github.com/ultramango/gear360reveng . With the info.tg - method it enters self-test mode, no internet connection possible. 

info.tgw works, gphoto-access over usb becomes possible, but only file transfer, no image capture.

**Comment by ottokiksmaler** [comment]
Sorry, I have only 2017 model and no access to 2016 one.

**Comment by FlorianFranzen** [comment]
The 2016 is not much different. You will just have to enable the Wifi in softap mode and hostapd before running telnet.

Here is what I use:
```
wlan.sh softap
hostapd -B -d /mnt/mmc/hostapd.conf -f/mnt/mmc/hostapd.log
ifconfig wlan0 192.168.0.1/24
```
You will have to put a valid ```hostapd.conf``` on the SD card as well, e.g for a simple unencrypted AP.
```
interface=wlan0
driver=nl80211
ssid=Gear360
hw_mode=g
channel=6
macaddr_acl=0
auth_algs=0
ignore_broadcast_ssid=0
```
