### ISSUE TITLE
This script works just from SD card?

### ISSUE THREAD

**Issue by LogicBypass** [ottokiksmaler/gear360_modding#13]
This script works just from sd card or it flash the firmware?

**Comment by ottokiksmaler** [comment]
It works from sd card.

**Comment by LogicBypass** [comment]
Thanks for mod, it works awesome! It is possible somehow to make live view to work using this type of connection (HTTP)?

**Comment by ottokiksmaler** [comment]
There were some attempts, but it's not likely to be added as Samsung has left the camera business (NX) and VR business (Gear is no more) and Google has left - noone wants to dedicate the time needed. Sorry.

**Comment by LogicBypass** [comment]
Just downloaded new firmware for R210 (SMR210GLU0AQC6)
link:
https://drive.google.com/file/d/161W5dT8w3didFc3khIrzvU5-mhQV29-c/view?usp=sharing
Did you know how to compile it or can leave instructions how to do it?
