### ISSUE TITLE
Bluetooth 

### ISSUE THREAD

**Issue by Etua** [ottokiksmaler/gear360_modding#6]
Gear360 also supports BT connection which can be used to activate the shutter when using official Samsung app. Is it possible that this set of mods would allow opening BT connection without Samsung toolkit? You can buy an external remote that is marketed as one that does that but I haven't checked whether it is true.

**Comment by Etua** [comment]
I think that Samsung released an official remote as an accessory so it should technically be possible.

**Comment by neuhaus** [comment]
A bluetooth remote app as a replacement for the standalone bt remote would be great.

**Comment by neuhaus** [comment]
Did you mean to close this as WONTFIX?

**Comment by ottokiksmaler** [comment]
Sorry, forgot to put a reason. It's just that I don't know how to implement it. If someone can provide any guidance and specifications for establishing connection and sending commands I'll reopen the issue.

In the meantime there is Wi-Fi that works from browser.

**Comment by Etua** [comment]
Would the source code obtained from Samsung be any help? I downloaded it and I saw that they even provide build instructions but I suppose that they might not be obligated to put the source/configuration responsible for the BT communications if it did not "touch" the GPL code.

**Comment by ottokiksmaler** [comment]
If you are talking about GPL'd code for kernel I already have it (nor NX500 IIRC, you could share one for Gear if you have it?) but we would need code for their remote control app (which they don't provide). Someone more knowledgeable in android and reverse engineering could probably do a lot with the APK but I don't have enough knowledge there.

**Comment by Etua** [comment]
I only have the contents of [this package](https://opensource.samsung.com/uploadSearch?searchValue=SM-R210). You may already be familiar with the XDA thread where someone altered the official app to run on non-Samsung devices and using it I got the BT functionality on my OPO.
