### ISSUE TITLE
Use Gear360 while charging cable plugged in?

### ISSUE THREAD

**Issue by Skygaze** [ottokiksmaler/gear360_modding#8]
Does anyone know how to set or mod the Gear360 so I can use it continuously for 12 hours? All of our phones we can use while plugged in, but not the Gear360 - very annoying to me. Looking for a mod where camera functions while plugged in.
Regards,
Alister.

**Comment by ottokiksmaler** [comment]
Sorry for the late reply, I use it plugged to external battery pack (generic one) and it works. It has to be cooled in hot environments (even a small breeze will do, indoors I mount a tiny fan under the tripod).
