### ISSUE TITLE
Source for keyscan360

### ISSUE THREAD

**Issue by MarkVillacampa** [ottokiksmaler/gear360_modding#9]
Hello!

I noticed the zip contains a modified version of the `keyscan` utility located in the [nx500_nx1_modding](https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/keyscan.c) repo.

Could you publish the changes you made to that file?

Thanks!

**Comment by ottokiksmaler** [comment]
Uploaded to https://github.com/ottokiksmaler/gear360_modding/blob/master/keyscan360.c
It was two additional buttons.
